[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask==3.1.0",
    "matplotlib==3.9.3",
    "numpy==2.1.3",
    "pandas==2.2.3",
]
